
baseurl: /Aman56/
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
title: "Aman Shukla"
description: "Lead Data Scientist at Resonate. Research in user behavior modeling, fairness in ML, and mechanistic interpretability."
og_image: /assets/images/aman.jpg

author:
  name: "Aman Shukla"
  avatar: "/assets/images/aman.jpg"
  bio: "Lead Data Scientist @ Resonate | NYU Alum"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:as14034@nyu.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/aman56shukla"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Aman56"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=dtBDI_oAAAAJ&hl=en&oi=ao"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
