title: Aman Shukla
description: "AI/ML Scientist <br><br> <a href='mailto:as14034@nyu.edu'>📧 Email</a> <br> <a href='https://linkedin.com/in/YOUR_PROFILE'>💼 LinkedIn</a> <br> <a href='https://github.com/YOUR_USERNAME'>💻 GitHub</a> <br> <a href='YOUR_SCHOLAR_URL'>🎓 Scholar</a>"
theme: jekyll-theme-dinky
